name: Early Music City
favicon: null
layout_spectrum: 0.9108120230957866
typography_spectrum: 0.09189801895990968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3311947004403919
  lightness: 0.8973504689056426
  saturation: 0.16546243871562183
  rhythmicContrast: 0.5372388714458793
purpose: []
